version: '3'

volumes:
  data:
    driver: local
  directslave:
    driver: local

services:
  directslave:
    image: powerkernel/directslave
    container_name: directslave
    restart: unless-stopped
    environment:
      - USER=admin
      - PASSWD=YOUR_PASSWORD
    ports:
      - target: 2224
        published: 2224
        protocol: tcp
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
    volumes:
      - data:/var/lib/bind/slave
      - directslave:/usr/local/directslave
